In [32]:
import numpy as np

## Part A- Create a Notebook to demonstrate NumPy Operations. [35 Points]

### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [33]:
firstArr = np.arange(start=1,stop=20, step=3)
firstArr

array([ 1,  4,  7, 10, 13, 16, 19])

### 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [34]:
secondArr = np.random.rand(3)
secondArr

array([0.16377799, 0.22510986, 0.92428365])

### 3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.


In [35]:
thirdArr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("First two row:\n", f"{thirdArr[0:2]}\n")
print("Last two row:\n", f"{thirdArr[1:3]}\n")

First two row:
 [[10 20 45]
 [30 12 16]]

Last two row:
 [[30 12 16]
 [42 17 56]]



### 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [36]:
fourthArr_1 = np.array([[2, 1], [2, 4]])
fourthArr_2 = np.array([[6, 5]])

vertical_adding = np.vstack((fourthArr_1, fourthArr_2))
print(vertical_adding)
horizontally_adding = np.hstack((fourthArr_1, fourthArr_2.reshape(2, -1)))
print(horizontally_adding)

split_arr = np.split(horizontally_adding, 2)
print(split_arr)

[[2 1]
 [2 4]
 [6 5]]
[[2 1 6]
 [2 4 5]]
[array([[2, 1, 6]]), array([[2, 4, 5]])]


### Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]])
- Is it possible to multiply these matrices?\
=> No, it couldn't to multiply with above array.
- Demonstrate the case when it is not possible to.\
=> The reason is that they have different shape. Otherwise, they should share same shape, like (3, 3) or (3 ,2)

In [37]:
x = np.array([[5, 7, 2],[4, 5, 6],[7, 4 ,2]])
y = np.array([[4, 2],[6, 2],[4, 2]])
# np.multiply(x, y) => Occur ValueError: operands could not be broadcast together with shapes (3,3) (3,2)
print("- Is it possible to multiply these matrices? \n => No, it couldn't to multiply with above array. Occur ValueError: operands could not be broadcast together with shapes (3,3) (3,2)\n- Demonstrate the case when it is not possible to.\n => The reason is that they have different shape. Otherwise, they should share same shape, like (3, 3) or (3 ,2)")

- Is it possible to multiply these matrices? 
 => No, it couldn't to multiply with above array. Occur ValueError: operands could not be broadcast together with shapes (3,3) (3,2)
- Demonstrate the case when it is not possible to.
 => The reason is that they have different shape. Otherwise, they should share same shape, like (3, 3) or (3 ,2)


### 6. Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2]),
- Find the Shape, Number of dimensions of vector x.
- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [38]:
x = np.array([2, -1, 8])
y = np.array([3, 1, -2])
x_shape = np.shape(x)
y_shape = np.shape(y)
print(f"x's shape is {x_shape}, y's shape is {y_shape}, they are one demension.\n")

reshapeX = x.reshape(3,1)
print(np.shape(reshapeX),"\n")
print(reshapeX,"\n")

print(f"The number of dimensions now is two.")




x's shape is (3,), y's shape is (3,), they are one demension.

(3, 1) 

[[ 2]
 [-1]
 [ 8]] 

The number of dimensions now is two.


### 7.How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

- How does broadcasting work? 

    > The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.\
    If I want to do a subtraction or multiplication on two array (3,3) */- (3,1) or (1,3), broadcasting would auto transfer the small array to fit the large one, like \
    [ [7], [1], [6] ] or [ [7, 1, 6] ] => [ [7, 7, 7], [1, 1, 1], [6, 6, 6] ]\
    to finish the operations (subtraction and multiplication)

In [39]:
threeXthree_M1 = np.random.randint(1, 10, size=(3,3))
print(threeXthree_M1, "\n")
threeXthree_M2 = np.random.randint(1, 10, size=(3,1))
print(threeXthree_M2, "\n")
threeXthree_M3 = np.random.randint(1, 10, size=(1,3))
print(threeXthree_M3, "\n")
print(threeXthree_M1 - threeXthree_M2, "\n")
print(threeXthree_M1 * threeXthree_M2)

[[8 1 9]
 [8 5 7]
 [6 4 8]] 

[[7]
 [1]
 [6]] 

[[3 4 2]] 

[[ 1 -6  2]
 [ 7  4  6]
 [ 0 -2  2]] 

[[56  7 63]
 [ 8  5  7]
 [36 24 48]]


## Part B- Linear Equations [15 Points]
Determine the singularity of the system of equations, comment on the expected solution of the system.
Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be
solved using NumPy functions.

> I believe NumPy could find the solution of linear equations, but it might include non-integer results. If there is a restriction for only integer-type solutions, then perhaps other methods need to be considered. Additionally, there is a function called 'allclose' that can be used to verify the answer.

> Then, it would return and raise a error called "Singular matrix" when the Linear Equation has no solution

### Part B.1
- 1. 4x + y - 2z = 10
- 2. 2x - 3y + 2z = -4
- 3. x + 2y + 3z = 6

In [40]:
A = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
b = np.array([10, -4, 6])

results = np.linalg.solve(A, b)
print(results)

np.allclose(np.dot(A, results), b)

# A = np.array([[2, 5,], [5, 2]])
# b = np.array([39, 24])

# results = np.linalg.solve(A, b)
# print(results)
# np.allclose(np.dot(A, results), b)

[ 1.8  2.4 -0.2]


True

### Part B.2
- 2x - y + 3z + 4w = 10
- 4x - 2y + 6z + 8w = 20
- 3x + y - 2z + 2w = 3
- x + 3y - 4z + w = -1

> This Linear Equation has no solution (sigular matrix), so it return and raise a error called "Singular matrix" like shown below.

In [41]:
A = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
b = np.array([10, 20, 3, -1])

results = np.linalg.solve(A, b)
print(results)

np.allclose(np.dot(A, results), b)

LinAlgError: Singular matrix